name: "ETL Pipeline"

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract data (example command)
      - name: Extract data
        run: echo "Data is extracted successfully"
